/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type Kommenttikoodi = {
  _id: string;
  _type: "kommenttikoodi";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  koodi?: string;
};

export type KaupunkiReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "kaupunki";
};

export type Etusivu = {
  _id: string;
  _type: "etusivu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroTitle?: string;
  heroDescription?: string;
  heroImage?: ImageWithAlt;
  heroCtas?: Array<{
    label?: string;
    href?: string;
    primary?: boolean;
    _key: string;
  }>;
  seuraavaOttelu?: {
    ottelu?: string;
    kilpailu?: string;
    aika?: string;
  };
  blocks?: Array<
    | {
        eyebrow?: string;
        heading?: string;
        count?: number;
        _type: "uutiset";
        _key: string;
      }
    | {
        ottelutHeading?: string;
        ottelutCount?: number;
        vainMaajoukkue?: boolean;
        seurat?: Array<string>;
        laskuri?: boolean;
        tapahtumatHeading?: string;
        tapahtumatCount?: number;
        _type: "otteluohjelma";
        _key: string;
      }
    | {
        heading?: string;
        count?: number;
        _type: "tapahtumat";
        _key: string;
      }
    | {
        eyebrow?: string;
        heading?: string;
        body?: PortableText;
        image?: ImageWithAlt;
        ctaLabel?: string;
        ctaHref?: string;
        _type: "esittely";
        _key: string;
      }
    | {
        eyebrow?: string;
        heading?: string;
        city?: KaupunkiReference;
        count?: number;
        _type: "ravintolatSpotlight";
        _key: string;
      }
    | {
        heading?: string;
        body?: string;
        ctaLabel?: string;
        ctaHref?: string;
        _type: "jalkapalloarkisto";
        _key: string;
      }
    | {
        heading?: string;
        count?: number;
        _type: "galleria";
        _key: string;
      }
    | {
        heading?: string;
        body?: string;
        ctaLabel?: string;
        ctaHref?: string;
        _type: "cta";
        _key: string;
      }
  >;
  legacyUrl?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        newTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type Asetukset = {
  _id: string;
  _type: "asetukset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  tagline?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  defaultOgImage?: ImageWithAlt;
  defaultSeoDescription?: string;
  heroFallback?: ImageWithAlt;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Navigaatio = {
  _id: string;
  _type: "navigaatio";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<{
    label?: string;
    href?: string;
    highlight?: boolean;
    children?: Array<{
      label?: string;
      href?: string;
      _key: string;
    }>;
    _key: string;
  }>;
};

export type Yhteystiedot = {
  _id: string;
  _type: "yhteystiedot";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  address?: string;
  postalCode?: string;
  city?: string;
  email?: string;
  phone?: string;
  yTunnus?: string;
  iban?: string;
  socials?: Array<{
    platform?: "youtube" | "facebook" | "instagram" | "linkedin" | "x";
    url?: string;
    _key: string;
  }>;
  location?: Geopoint;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type UutinenReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "uutinen";
};

export type Kommentti = {
  _id: string;
  _type: "kommentti";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  piilotettu?: boolean;
  uutinen?: UutinenReference;
  nimi?: string;
  teksti?: string;
  veikkaus?: {
    jarjestys?: Array<string>;
    maalikuningas?: string;
  };
  lahetetty?: string;
  lahde?: "sivusto" | "blogspot";
  blogspotId?: string;
};

export type JalkapalloTilastoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "jalkapalloTilasto";
};

export type Pelaaja = {
  _id: string;
  _type: "pelaaja";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  tiivistelma?: string;
  syntymaaika?: string;
  pelipaikka?: "maalivahti" | "puolustaja" | "keskikentta" | "hyokkaaja";
  maaottelut?: number;
  maalit?: number;
  seurat?: Array<{
    seura?: string;
    alkuvuosi?: number;
    loppuvuosi?: number;
    _key: string;
  }>;
  kuvaus?: PortableText;
  tilastot?: Array<
    {
      _key: string;
    } & JalkapalloTilastoReference
  >;
  kuvat?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  needsReview?: boolean;
  tarkistettavaa?: string;
  seoTitle?: string;
  seoDescription?: string;
  legacyUrl?: string;
  muutLegacyUrlit?: Array<string>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Arvokisa = {
  _id: string;
  _type: "arvokisa";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tiivistelma?: string;
  kisatyyppi?:
    "mm" | "em" | "kansojen-liiga" | "olympialaiset" | "u21-em" | "muu";
  vuosi?: number;
  isantamaat?: Array<string>;
  alkuPvm?: string;
  loppuPvm?: string;
  voittaja?: string;
  hopea?: string;
  pronssi?: string;
  suomenSijoitus?: string;
  kuvaus?: PortableText;
  tilastot?: Array<
    {
      _key: string;
    } & JalkapalloTilastoReference
  >;
  kuvat?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  needsReview?: boolean;
  tarkistettavaa?: string;
  seoTitle?: string;
  seoDescription?: string;
  legacyUrl?: string;
  muutLegacyUrlit?: Array<string>;
};

export type KlubiToiminta = {
  _id: string;
  _type: "klubiToiminta";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tiivistelma?: string;
  kuvaus?: PortableText;
  jarjestys?: number;
  kuvat?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  vuodet?: Array<{
    vuosi?: number;
    paivamaara?: string;
    otsikko?: string;
    jarjestysnumero?: number;
    paikka?: string;
    osallistujat?: Array<string>;
    kuvaus?: string;
    linkki?: {
      url?: string;
      teksti?: string;
    };
    kuvat?: Array<
      {
        _key: string;
      } & ImageWithAlt
    >;
    _key: string;
  }>;
  tilastot?: Array<
    {
      _key: string;
    } & JalkapalloTilastoReference
  >;
  needsReview?: boolean;
  tarkistettavaa?: string;
  seoTitle?: string;
  seoDescription?: string;
  legacyUrl?: string;
  muutLegacyUrlit?: Array<string>;
};

export type TapahtumaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tapahtuma";
};

export type GalleriaAlbumi = {
  _id: string;
  _type: "galleriaAlbumi";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tiivistelma?: string;
  date?: string;
  event?: TapahtumaReference;
  coverImage?: ImageWithAlt;
  images?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  needsReview?: boolean;
  tarkistettavaa?: string;
  legacyUrl?: string;
};

export type JalkapalloTilasto = {
  _id: string;
  _type: "jalkapalloTilasto";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tiivistelma?: string;
  category?:
    | "fifa-ranking"
    | "champions"
    | "huuhkajat"
    | "valmentajat"
    | "valmentajien-palkat"
    | "vuoden-pelaaja"
    | "lupaavat"
    | "ballon-dor"
    | "saavutukset"
    | "eurocup"
    | "uefa-cup"
    | "super-cup"
    | "conference-league"
    | "intercontinental"
    | "karsinta"
    | "arvokisa"
    | "pelaaja"
    | "ulkomaiset-mestarit"
    | "palloliitto"
    | "klubi"
    | "muu";
  huuhkajatOsio?:
    | "pelaajatilastot"
    | "huuhkaja-arvostelu"
    | "kansojen-liiga"
    | "avauskokoonpano"
    | "englanti"
    | "muut";
  intro?: PortableText;
  columns?: Array<{
    key?: string;
    label?: string;
    type?: "text" | "number" | "date" | "year" | "link";
    _key: string;
  }>;
  rows?: Array<{
    cells?: Array<{
      key?: string;
      value?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  lisatiedot?: PortableText;
  paivitetty?: string;
  jarjestys?: number;
  kuvat?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  sources?: Array<string>;
  needsReview?: boolean;
  tarkistettavaa?: string;
  seoTitle?: string;
  seoDescription?: string;
  legacyUrl?: string;
  muutLegacyUrlit?: Array<string>;
};

export type Stadion = {
  _id: string;
  _type: "stadion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  tiivistelma?: string;
  city?: KaupunkiReference;
  address?: string;
  location?: Geopoint;
  capacity?: number;
  openedYear?: number;
  description?: PortableText;
  images?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  needsReview?: boolean;
  tarkistettavaa?: string;
  seoTitle?: string;
  seoDescription?: string;
  legacyUrl?: string;
  muutLegacyUrlit?: Array<string>;
};

export type RavintolaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "ravintola";
};

export type RavintolaKayttajaArvostelu = {
  _id: string;
  _type: "ravintolaKayttajaArvostelu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  reviewerName?: string;
  ehdotettuRavintola?: {
    nimi?: string;
    kaupunki?: string;
    maa?: string;
    lisatieto?: string;
  };
  restaurant?: RavintolaReference;
  stars?: number;
  comment?: string;
  submittedAt?: string;
};

export type Ravintola = {
  _id: string;
  _type: "ravintola";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  tiivistelma?: string;
  city?: KaupunkiReference;
  address?: string;
  postalCode?: string;
  location?: Geopoint;
  phone?: string;
  website?: string;
  cuisine?: Array<string>;
  priceLevel?: "\u20AC" | "\u20AC\u20AC" | "\u20AC\u20AC\u20AC";
  stars?: number;
  ratingOverall?: number;
  ratingFood?: number;
  ratingPrice?: number;
  ratingAtmosphere?: number;
  tuomio?: string;
  stadionHuomio?: string;
  review?: PortableText;
  ottelupaivana?: string;
  pros?: Array<string>;
  cons?: Array<string>;
  visitedAt?: string;
  visits?: Array<string>;
  visitContext?: string;
  closed?: boolean;
  closedNote?: string;
  images?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  needsReview?: boolean;
  tarkistettavaa?: string;
  seoTitle?: string;
  seoDescription?: string;
  legacyUrl?: string;
  muutLegacyUrlit?: Array<string>;
};

export type Kaupunki = {
  _id: string;
  _type: "kaupunki";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  country?: string;
  maakunta?:
    | "uusimaa"
    | "varsinais-suomi"
    | "satakunta"
    | "kanta-hame"
    | "pirkanmaa"
    | "paijat-hame"
    | "kymenlaakso"
    | "etela-karjala"
    | "etela-savo"
    | "pohjois-savo"
    | "pohjois-karjala"
    | "keski-suomi"
    | "etela-pohjanmaa"
    | "pohjanmaa"
    | "keski-pohjanmaa"
    | "pohjois-pohjanmaa"
    | "kainuu"
    | "lappi"
    | "ahvenanmaa";
};

export type HallitusJasenReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "hallitusJasen";
};

export type Uutinen = {
  _id: string;
  _type: "uutinen";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tiivistelma?: string;
  publishedAt?: string;
  excerpt?: string;
  coverImage?: ImageWithAlt;
  body?: PortableText;
  ulkoinenLinkki?: string;
  lahde?: {
    nimi?: string;
    url?: string;
    pvm?: string;
  };
  categories?: Array<string>;
  author?: HallitusJasenReference;
  needsReview?: boolean;
  tarkistettavaa?: string;
  kommentointi?: {
    kaytossa?: boolean;
    tyyppi?: "kommentti" | "sarjajarjestys" | "voittajaveikkaus";
    sulkeutuu?: string;
    vaihtoehdot?: Array<string>;
    sijoituksia?: number;
    maalikuningas?: boolean;
    ohje?: string;
  };
  seoTitle?: string;
  seoDescription?: string;
  legacyUrl?: string;
  muutLegacyUrlit?: Array<string>;
  blogspot?: {
    id?: string;
    url?: string;
    polku?: string;
    tunnisteet?: Array<string>;
    kommentteja?: number;
  };
};

export type HallitusJasen = {
  _id: string;
  _type: "hallitusJasen";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  image?: ImageWithAlt;
  bio?: string;
  email?: string;
  phone?: string;
  order?: number;
};

export type Ottelu = {
  _id: string;
  _type: "ottelu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  aika?: string;
  koti?: string;
  vieras?: string;
  kilpailu?: string;
  stadion?: string;
  klubiPaikalla?: boolean;
  vierasmatka?: boolean;
};

export type Tapahtuma = {
  _id: string;
  _type: "tapahtuma";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tiivistelma?: string;
  startsAt?: string;
  endsAt?: string;
  location?: string;
  juhla?: boolean;
  image?: ImageWithAlt;
  description?: PortableText;
  signupUrl?: string;
  signupEmail?: string;
  needsReview?: boolean;
  tarkistettavaa?: string;
  seoTitle?: string;
  seoDescription?: string;
  legacyUrl?: string;
};

export type Sivu = {
  _id: string;
  _type: "sivu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tiivistelma?: string;
  hero?: ImageWithAlt;
  ingress?: string;
  body?: PortableText;
  tilastot?: Array<
    {
      _key: string;
    } & JalkapalloTilastoReference
  >;
  needsReview?: boolean;
  tarkistettavaa?: string;
  seoTitle?: string;
  seoDescription?: string;
  legacyUrl?: string;
  muutLegacyUrlit?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | Kommenttikoodi
  | KaupunkiReference
  | Etusivu
  | SanityImageAssetReference
  | ImageWithAlt
  | PortableText
  | Asetukset
  | SanityImageCrop
  | SanityImageHotspot
  | Navigaatio
  | Yhteystiedot
  | Geopoint
  | UutinenReference
  | Kommentti
  | JalkapalloTilastoReference
  | Pelaaja
  | Slug
  | Arvokisa
  | KlubiToiminta
  | TapahtumaReference
  | GalleriaAlbumi
  | JalkapalloTilasto
  | Stadion
  | RavintolaReference
  | RavintolaKayttajaArvostelu
  | Ravintola
  | Kaupunki
  | HallitusJasenReference
  | Uutinen
  | HallitusJasen
  | Ottelu
  | Tapahtuma
  | Sivu
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: sanity/lib/queries/arkisto-laajennus.ts
// Variable: arvokisatListQuery
// Query: *[_type == "arvokisa" && defined(slug.current)] | order(vuosi desc, title asc){    _id,    title,    "slug": slug.current,    tiivistelma,    kisatyyppi,    vuosi,    isantamaat,    voittaja,    suomenSijoitus  }
export type ArvokisatListQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  tiivistelma: string | null;
  kisatyyppi:
    "em" | "kansojen-liiga" | "mm" | "muu" | "olympialaiset" | "u21-em" | null;
  vuosi: number | null;
  isantamaat: Array<string> | null;
  voittaja: string | null;
  suomenSijoitus: string | null;
}>;

// Source: sanity/lib/queries/arkisto-laajennus.ts
// Variable: arvokisaSlugsQuery
// Query: *[_type == "arvokisa" && defined(slug.current)][].slug.current
export type ArvokisaSlugsQueryResult = Array<string | null>;

// Source: sanity/lib/queries/arkisto-laajennus.ts
// Variable: arvokisaBySlugQuery
// Query: *[_type == "arvokisa" && slug.current == $slug][0]{    _id,    _updatedAt,    title,    "slug": slug.current,    tiivistelma,    kisatyyppi,    vuosi,    isantamaat,    voittaja,    suomenSijoitus,    alkuPvm,    loppuPvm,    hopea,    pronssi,    kuvaus,    tilastot[]->{      _id,      _updatedAt,      title,      "slug": slug.current,      tiivistelma,      category,      intro,      columns[]{ key, label, type },      rows[]{ cells[]{ key, value } },      lisatiedot,      kuvat[]{ _key, alt, caption, asset, hotspot, crop },      paivitetty,      jarjestys,      "sources": coalesce(sources, [])    },    kuvat[]{ _key, alt, caption, asset, hotspot, crop },    seoTitle,    seoDescription  }
export type ArvokisaBySlugQueryResult = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  tiivistelma: string | null;
  kisatyyppi:
    "em" | "kansojen-liiga" | "mm" | "muu" | "olympialaiset" | "u21-em" | null;
  vuosi: number | null;
  isantamaat: Array<string> | null;
  voittaja: string | null;
  suomenSijoitus: string | null;
  alkuPvm: string | null;
  loppuPvm: string | null;
  hopea: string | null;
  pronssi: string | null;
  kuvaus: PortableText | null;
  tilastot: Array<{
    _id: string;
    _updatedAt: string;
    title: string | null;
    slug: string | null;
    tiivistelma: string | null;
    category:
      | "arvokisa"
      | "ballon-dor"
      | "champions"
      | "conference-league"
      | "eurocup"
      | "fifa-ranking"
      | "huuhkajat"
      | "intercontinental"
      | "karsinta"
      | "klubi"
      | "lupaavat"
      | "muu"
      | "palloliitto"
      | "pelaaja"
      | "saavutukset"
      | "super-cup"
      | "uefa-cup"
      | "ulkomaiset-mestarit"
      | "valmentajat"
      | "valmentajien-palkat"
      | "vuoden-pelaaja"
      | null;
    intro: PortableText | null;
    columns: Array<{
      key: string | null;
      label: string | null;
      type: "date" | "link" | "number" | "text" | "year" | null;
    }> | null;
    rows: Array<{
      cells: Array<{
        key: string | null;
        value: string | null;
      }> | null;
    }> | null;
    lisatiedot: PortableText | null;
    kuvat: Array<{
      _key: string;
      alt: string | null;
      caption: string | null;
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    }> | null;
    paivitetty: string | null;
    jarjestys: number | null;
    sources: Array<string> | Array<never>;
  }> | null;
  kuvat: Array<{
    _key: string;
    alt: string | null;
    caption: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: sanity/lib/queries/arkisto-laajennus.ts
// Variable: arvokisaMitalitaulukotQuery
// Query: *[    _type == "jalkapalloTilasto"    && category == "arvokisa"    && count(*[_type == "arvokisa" && references(^._id)]) == 0  ] | order(coalesce(jarjestys, 1000) asc, title asc){    _id,      _updatedAt,      title,      "slug": slug.current,      tiivistelma,      category,      intro,      columns[]{ key, label, type },      rows[]{ cells[]{ key, value } },      lisatiedot,      kuvat[]{ _key, alt, caption, asset, hotspot, crop },      paivitetty,      jarjestys,      "sources": coalesce(sources, [])  }
export type ArvokisaMitalitaulukotQueryResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  tiivistelma: string | null;
  category:
    | "arvokisa"
    | "ballon-dor"
    | "champions"
    | "conference-league"
    | "eurocup"
    | "fifa-ranking"
    | "huuhkajat"
    | "intercontinental"
    | "karsinta"
    | "klubi"
    | "lupaavat"
    | "muu"
    | "palloliitto"
    | "pelaaja"
    | "saavutukset"
    | "super-cup"
    | "uefa-cup"
    | "ulkomaiset-mestarit"
    | "valmentajat"
    | "valmentajien-palkat"
    | "vuoden-pelaaja"
    | null;
  intro: PortableText | null;
  columns: Array<{
    key: string | null;
    label: string | null;
    type: "date" | "link" | "number" | "text" | "year" | null;
  }> | null;
  rows: Array<{
    cells: Array<{
      key: string | null;
      value: string | null;
    }> | null;
  }> | null;
  lisatiedot: PortableText | null;
  kuvat: Array<{
    _key: string;
    alt: string | null;
    caption: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  paivitetty: string | null;
  jarjestys: number | null;
  sources: Array<string> | Array<never>;
}>;

// Source: sanity/lib/queries/arkisto-laajennus.ts
// Variable: arvokisatRelatedQuery
// Query: *[_type == "arvokisa" && defined(slug.current)    && slug.current != $slug    && kisatyyppi == $kisatyyppi] | order(vuosi desc)[0...4]{    _id,    title,    "slug": slug.current,    tiivistelma,    kisatyyppi,    vuosi,    isantamaat,    voittaja,    suomenSijoitus  }
export type ArvokisatRelatedQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  tiivistelma: string | null;
  kisatyyppi:
    "em" | "kansojen-liiga" | "mm" | "muu" | "olympialaiset" | "u21-em" | null;
  vuosi: number | null;
  isantamaat: Array<string> | null;
  voittaja: string | null;
  suomenSijoitus: string | null;
}>;

// Source: sanity/lib/queries/arkisto-laajennus.ts
// Variable: pelaajatListQuery
// Query: *[_type == "pelaaja" && defined(slug.current)] | order(name asc){    _id,    name,    "slug": slug.current,    tiivistelma,    pelipaikka,    maaottelut,    maalit,    "kuva": kuvat[0]{ alt, caption, asset, hotspot, crop }  }
export type PelaajatListQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  tiivistelma: string | null;
  pelipaikka: "hyokkaaja" | "keskikentta" | "maalivahti" | "puolustaja" | null;
  maaottelut: number | null;
  maalit: number | null;
  kuva: {
    alt: string | null;
    caption: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: sanity/lib/queries/arkisto-laajennus.ts
// Variable: pelaajaSlugsQuery
// Query: *[_type == "pelaaja" && defined(slug.current)][].slug.current
export type PelaajaSlugsQueryResult = Array<string | null>;

// Source: sanity/lib/queries/arkisto-laajennus.ts
// Variable: pelaajaBySlugQuery
// Query: *[_type == "pelaaja" && slug.current == $slug][0]{    _id,    _updatedAt,    name,    "slug": slug.current,    tiivistelma,    pelipaikka,    maaottelut,    maalit,    syntymaaika,    seurat[]{ _key, seura, alkuvuosi, loppuvuosi },    kuvaus,    tilastot[]->{      _id,      _updatedAt,      title,      "slug": slug.current,      tiivistelma,      category,      intro,      columns[]{ key, label, type },      rows[]{ cells[]{ key, value } },      lisatiedot,      kuvat[]{ _key, alt, caption, asset, hotspot, crop },      paivitetty,      jarjestys,      "sources": coalesce(sources, [])    },    kuvat[]{ _key, alt, caption, asset, hotspot, crop },    seoTitle,    seoDescription  }
export type PelaajaBySlugQueryResult = {
  _id: string;
  _updatedAt: string;
  name: string | null;
  slug: string | null;
  tiivistelma: string | null;
  pelipaikka: "hyokkaaja" | "keskikentta" | "maalivahti" | "puolustaja" | null;
  maaottelut: number | null;
  maalit: number | null;
  syntymaaika: string | null;
  seurat: Array<{
    _key: string;
    seura: string | null;
    alkuvuosi: number | null;
    loppuvuosi: number | null;
  }> | null;
  kuvaus: PortableText | null;
  tilastot: Array<{
    _id: string;
    _updatedAt: string;
    title: string | null;
    slug: string | null;
    tiivistelma: string | null;
    category:
      | "arvokisa"
      | "ballon-dor"
      | "champions"
      | "conference-league"
      | "eurocup"
      | "fifa-ranking"
      | "huuhkajat"
      | "intercontinental"
      | "karsinta"
      | "klubi"
      | "lupaavat"
      | "muu"
      | "palloliitto"
      | "pelaaja"
      | "saavutukset"
      | "super-cup"
      | "uefa-cup"
      | "ulkomaiset-mestarit"
      | "valmentajat"
      | "valmentajien-palkat"
      | "vuoden-pelaaja"
      | null;
    intro: PortableText | null;
    columns: Array<{
      key: string | null;
      label: string | null;
      type: "date" | "link" | "number" | "text" | "year" | null;
    }> | null;
    rows: Array<{
      cells: Array<{
        key: string | null;
        value: string | null;
      }> | null;
    }> | null;
    lisatiedot: PortableText | null;
    kuvat: Array<{
      _key: string;
      alt: string | null;
      caption: string | null;
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    }> | null;
    paivitetty: string | null;
    jarjestys: number | null;
    sources: Array<string> | Array<never>;
  }> | null;
  kuvat: Array<{
    _key: string;
    alt: string | null;
    caption: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: sanity/lib/queries/arkisto-laajennus.ts
// Variable: pelaajatRelatedQuery
// Query: *[_type == "pelaaja" && defined(slug.current) && slug.current != $slug]    | order(coalesce(maaottelut, 0) desc, name asc)[0...4]{    _id,    name,    "slug": slug.current,    tiivistelma,    pelipaikka,    maaottelut,    maalit,    "kuva": kuvat[0]{ alt, caption, asset, hotspot, crop }  }
export type PelaajatRelatedQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  tiivistelma: string | null;
  pelipaikka: "hyokkaaja" | "keskikentta" | "maalivahti" | "puolustaja" | null;
  maaottelut: number | null;
  maalit: number | null;
  kuva: {
    alt: string | null;
    caption: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: sanity/lib/queries/arkisto-laajennus.ts
// Variable: stadionitListQuery
// Query: *[_type == "stadion" && defined(slug.current)]    | order(city->country asc, name asc){    _id,    name,    "slug": slug.current,    tiivistelma,    capacity,    openedYear,    "city": city->{ name, "slug": slug.current, country },    "kuva": images[0]{ alt, caption, asset, hotspot, crop }  }
export type StadionitListQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  tiivistelma: string | null;
  capacity: number | null;
  openedYear: number | null;
  city: {
    name: string | null;
    slug: string | null;
    country: string | null;
  } | null;
  kuva: {
    alt: string | null;
    caption: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: sanity/lib/queries/arkisto-laajennus.ts
// Variable: stadionSlugsQuery
// Query: *[_type == "stadion" && defined(slug.current)][].slug.current
export type StadionSlugsQueryResult = Array<string | null>;

// Source: sanity/lib/queries/arkisto-laajennus.ts
// Variable: stadionBySlugQuery
// Query: *[_type == "stadion" && slug.current == $slug][0]{    _id,    _updatedAt,    name,    "slug": slug.current,    tiivistelma,    capacity,    openedYear,    address,    "city": city->{ name, "slug": slug.current, country },    location{ lat, lng, alt },    description,    images[]{ _key, alt, caption, asset, hotspot, crop },    seoTitle,    seoDescription  }
export type StadionBySlugQueryResult = {
  _id: string;
  _updatedAt: string;
  name: string | null;
  slug: string | null;
  tiivistelma: string | null;
  capacity: number | null;
  openedYear: number | null;
  address: string | null;
  city: {
    name: string | null;
    slug: string | null;
    country: string | null;
  } | null;
  location: {
    lat: number | null;
    lng: number | null;
    alt: number | null;
  } | null;
  description: PortableText | null;
  images: Array<{
    _key: string;
    alt: string | null;
    caption: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: sanity/lib/queries/arkisto-laajennus.ts
// Variable: stadionitRelatedQuery
// Query: *[_type == "stadion" && defined(slug.current) && slug.current != $slug]    | order(select(city->name == $cityName => 0, 1) asc, name asc)[0...4]{    _id,    name,    "slug": slug.current,    tiivistelma,    capacity,    openedYear,    "city": city->{ name, "slug": slug.current, country },    "kuva": images[0]{ alt, caption, asset, hotspot, crop }  }
export type StadionitRelatedQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  tiivistelma: string | null;
  capacity: number | null;
  openedYear: number | null;
  city: {
    name: string | null;
    slug: string | null;
    country: string | null;
  } | null;
  kuva: {
    alt: string | null;
    caption: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: sanity/lib/queries/arkisto.ts
// Variable: tilastotByCategoryQuery
// Query: *[_type == "jalkapalloTilasto" && category == $category]    | order(coalesce(jarjestys, 1000) asc, title asc){      _id,  _updatedAt,  title,  "slug": slug.current,  tiivistelma,  category,  huuhkajatOsio,  intro,  columns[]{ key, label, type },  rows[]{ cells[]{ key, value } },  lisatiedot,  kuvat[]{ _key, alt, caption, asset, hotspot, crop },  paivitetty,  jarjestys,  "sources": coalesce(sources, [])  }
export type TilastotByCategoryQueryResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  tiivistelma: string | null;
  category:
    | "arvokisa"
    | "ballon-dor"
    | "champions"
    | "conference-league"
    | "eurocup"
    | "fifa-ranking"
    | "huuhkajat"
    | "intercontinental"
    | "karsinta"
    | "klubi"
    | "lupaavat"
    | "muu"
    | "palloliitto"
    | "pelaaja"
    | "saavutukset"
    | "super-cup"
    | "uefa-cup"
    | "ulkomaiset-mestarit"
    | "valmentajat"
    | "valmentajien-palkat"
    | "vuoden-pelaaja"
    | null;
  huuhkajatOsio:
    | "avauskokoonpano"
    | "englanti"
    | "huuhkaja-arvostelu"
    | "kansojen-liiga"
    | "muut"
    | "pelaajatilastot"
    | null;
  intro: PortableText | null;
  columns: Array<{
    key: string | null;
    label: string | null;
    type: "date" | "link" | "number" | "text" | "year" | null;
  }> | null;
  rows: Array<{
    cells: Array<{
      key: string | null;
      value: string | null;
    }> | null;
  }> | null;
  lisatiedot: PortableText | null;
  kuvat: Array<{
    _key: string;
    alt: string | null;
    caption: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  paivitetty: string | null;
  jarjestys: number | null;
  sources: Array<string> | Array<never>;
}>;

// Source: sanity/lib/queries/arkisto.ts
// Variable: tilastotByCategoriesQuery
// Query: *[_type == "jalkapalloTilasto" && category in $categories]    | order(coalesce(jarjestys, 1000) asc, title asc){      _id,  _updatedAt,  title,  "slug": slug.current,  tiivistelma,  category,  huuhkajatOsio,  intro,  columns[]{ key, label, type },  rows[]{ cells[]{ key, value } },  lisatiedot,  kuvat[]{ _key, alt, caption, asset, hotspot, crop },  paivitetty,  jarjestys,  "sources": coalesce(sources, [])  }
export type TilastotByCategoriesQueryResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  tiivistelma: string | null;
  category:
    | "arvokisa"
    | "ballon-dor"
    | "champions"
    | "conference-league"
    | "eurocup"
    | "fifa-ranking"
    | "huuhkajat"
    | "intercontinental"
    | "karsinta"
    | "klubi"
    | "lupaavat"
    | "muu"
    | "palloliitto"
    | "pelaaja"
    | "saavutukset"
    | "super-cup"
    | "uefa-cup"
    | "ulkomaiset-mestarit"
    | "valmentajat"
    | "valmentajien-palkat"
    | "vuoden-pelaaja"
    | null;
  huuhkajatOsio:
    | "avauskokoonpano"
    | "englanti"
    | "huuhkaja-arvostelu"
    | "kansojen-liiga"
    | "muut"
    | "pelaajatilastot"
    | null;
  intro: PortableText | null;
  columns: Array<{
    key: string | null;
    label: string | null;
    type: "date" | "link" | "number" | "text" | "year" | null;
  }> | null;
  rows: Array<{
    cells: Array<{
      key: string | null;
      value: string | null;
    }> | null;
  }> | null;
  lisatiedot: PortableText | null;
  kuvat: Array<{
    _key: string;
    alt: string | null;
    caption: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  paivitetty: string | null;
  jarjestys: number | null;
  sources: Array<string> | Array<never>;
}>;

// Source: sanity/lib/queries/arkisto.ts
// Variable: tilastoBySlugQuery
// Query: *[    _type == "jalkapalloTilasto"    && category == $category    && slug.current == $slug  ][0]{      _id,  _updatedAt,  title,  "slug": slug.current,  tiivistelma,  category,  huuhkajatOsio,  intro,  columns[]{ key, label, type },  rows[]{ cells[]{ key, value } },  lisatiedot,  kuvat[]{ _key, alt, caption, asset, hotspot, crop },  paivitetty,  jarjestys,  "sources": coalesce(sources, [])  }
export type TilastoBySlugQueryResult = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  tiivistelma: string | null;
  category:
    | "arvokisa"
    | "ballon-dor"
    | "champions"
    | "conference-league"
    | "eurocup"
    | "fifa-ranking"
    | "huuhkajat"
    | "intercontinental"
    | "karsinta"
    | "klubi"
    | "lupaavat"
    | "muu"
    | "palloliitto"
    | "pelaaja"
    | "saavutukset"
    | "super-cup"
    | "uefa-cup"
    | "ulkomaiset-mestarit"
    | "valmentajat"
    | "valmentajien-palkat"
    | "vuoden-pelaaja"
    | null;
  huuhkajatOsio:
    | "avauskokoonpano"
    | "englanti"
    | "huuhkaja-arvostelu"
    | "kansojen-liiga"
    | "muut"
    | "pelaajatilastot"
    | null;
  intro: PortableText | null;
  columns: Array<{
    key: string | null;
    label: string | null;
    type: "date" | "link" | "number" | "text" | "year" | null;
  }> | null;
  rows: Array<{
    cells: Array<{
      key: string | null;
      value: string | null;
    }> | null;
  }> | null;
  lisatiedot: PortableText | null;
  kuvat: Array<{
    _key: string;
    alt: string | null;
    caption: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  paivitetty: string | null;
  jarjestys: number | null;
  sources: Array<string> | Array<never>;
} | null;

// Source: sanity/lib/queries/arkisto.ts
// Variable: tilastoSlugsByCategoryQuery
// Query: *[    _type == "jalkapalloTilasto"    && category == $category    && defined(slug.current)  ].slug.current
export type TilastoSlugsByCategoryQueryResult = Array<string | null>;

// Source: sanity/lib/queries/arkisto.ts
// Variable: huuhkajatHubQuery
// Query: {  "taulukot": *[_type == "jalkapalloTilasto" && category == "huuhkajat"]    | order(coalesce(jarjestys, 1000) asc, title asc){   _id,  _updatedAt,  title,  "slug": slug.current,  tiivistelma,  huuhkajatOsio },  "karsinnat": *[    _type == "jalkapalloTilasto" && category == "karsinta" && defined(slug.current)  ] | order(coalesce(jarjestys, 1000) asc, title asc){   _id,  _updatedAt,  title,  "slug": slug.current,  tiivistelma,  huuhkajatOsio }}
export type HuuhkajatHubQueryResult = {
  taulukot: Array<{
    _id: string;
    _updatedAt: string;
    title: string | null;
    slug: string | null;
    tiivistelma: string | null;
    huuhkajatOsio:
      | "avauskokoonpano"
      | "englanti"
      | "huuhkaja-arvostelu"
      | "kansojen-liiga"
      | "muut"
      | "pelaajatilastot"
      | null;
  }>;
  karsinnat: Array<{
    _id: string;
    _updatedAt: string;
    title: string | null;
    slug: string | null;
    tiivistelma: string | null;
    huuhkajatOsio:
      | "avauskokoonpano"
      | "englanti"
      | "huuhkaja-arvostelu"
      | "kansojen-liiga"
      | "muut"
      | "pelaajatilastot"
      | null;
  }>;
};

// Source: sanity/lib/queries/arkisto.ts
// Variable: huuhkajatOsioQuery
// Query: *[    _type == "jalkapalloTilasto"    && category == "huuhkajat"    && select(      $osio == $oletus => !(huuhkajatOsio in $tunnetut),      huuhkajatOsio == $osio    )  ] | order(coalesce(jarjestys, 1000) asc, title asc){      _id,  _updatedAt,  title,  "slug": slug.current,  tiivistelma,  category,  huuhkajatOsio,  intro,  columns[]{ key, label, type },  rows[]{ cells[]{ key, value } },  lisatiedot,  kuvat[]{ _key, alt, caption, asset, hotspot, crop },  paivitetty,  jarjestys,  "sources": coalesce(sources, [])  }
export type HuuhkajatOsioQueryResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  tiivistelma: string | null;
  category:
    | "arvokisa"
    | "ballon-dor"
    | "champions"
    | "conference-league"
    | "eurocup"
    | "fifa-ranking"
    | "huuhkajat"
    | "intercontinental"
    | "karsinta"
    | "klubi"
    | "lupaavat"
    | "muu"
    | "palloliitto"
    | "pelaaja"
    | "saavutukset"
    | "super-cup"
    | "uefa-cup"
    | "ulkomaiset-mestarit"
    | "valmentajat"
    | "valmentajien-palkat"
    | "vuoden-pelaaja"
    | null;
  huuhkajatOsio:
    | "avauskokoonpano"
    | "englanti"
    | "huuhkaja-arvostelu"
    | "kansojen-liiga"
    | "muut"
    | "pelaajatilastot"
    | null;
  intro: PortableText | null;
  columns: Array<{
    key: string | null;
    label: string | null;
    type: "date" | "link" | "number" | "text" | "year" | null;
  }> | null;
  rows: Array<{
    cells: Array<{
      key: string | null;
      value: string | null;
    }> | null;
  }> | null;
  lisatiedot: PortableText | null;
  kuvat: Array<{
    _key: string;
    alt: string | null;
    caption: string | null;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  paivitetty: string | null;
  jarjestys: number | null;
  sources: Array<string> | Array<never>;
}>;

// Source: sanity/lib/queries/arkisto.ts
// Variable: arkistoSummaryQuery
// Query: *[_type == "jalkapalloTilasto" && defined(category)]{    category,    "updatedAt": _updatedAt  }
export type ArkistoSummaryQueryResult = Array<{
  category:
    | "arvokisa"
    | "ballon-dor"
    | "champions"
    | "conference-league"
    | "eurocup"
    | "fifa-ranking"
    | "huuhkajat"
    | "intercontinental"
    | "karsinta"
    | "klubi"
    | "lupaavat"
    | "muu"
    | "palloliitto"
    | "pelaaja"
    | "saavutukset"
    | "super-cup"
    | "uefa-cup"
    | "ulkomaiset-mestarit"
    | "valmentajat"
    | "valmentajien-palkat"
    | "vuoden-pelaaja";
  updatedAt: string;
}>;

// Source: sanity/lib/queries/etusivu.ts
// Variable: etusivuQuery
// Query: *[_type == "etusivu"][0]{    heroEyebrow,    heroTitle,    heroDescription,    heroImage,    heroCtas[]{ label, href, primary },    seuraavaOttelu{ ottelu, kilpailu, aika },    blocks[]{      _type,      _key,      eyebrow,      heading,      count,      ottelutHeading,      ottelutCount,      vainMaajoukkue,      seurat,      laskuri,      tapahtumatHeading,      tapahtumatCount,      body,      image,      ctaLabel,      ctaHref,      "city": city->{ "_ref": _id, name }    }  }
export type EtusivuQueryResult = {
  heroEyebrow: string | null;
  heroTitle: string | null;
  heroDescription: string | null;
  heroImage: ImageWithAlt | null;
  heroCtas: Array<{
    label: string | null;
    href: string | null;
    primary: boolean | null;
  }> | null;
  seuraavaOttelu: {
    ottelu: string | null;
    kilpailu: string | null;
    aika: string | null;
  } | null;
  blocks: Array<
    | {
        _type: "cta";
        _key: string;
        eyebrow: null;
        heading: string | null;
        count: null;
        ottelutHeading: null;
        ottelutCount: null;
        vainMaajoukkue: null;
        seurat: null;
        laskuri: null;
        tapahtumatHeading: null;
        tapahtumatCount: null;
        body: string | null;
        image: null;
        ctaLabel: string | null;
        ctaHref: string | null;
        city: null;
      }
    | {
        _type: "esittely";
        _key: string;
        eyebrow: string | null;
        heading: string | null;
        count: null;
        ottelutHeading: null;
        ottelutCount: null;
        vainMaajoukkue: null;
        seurat: null;
        laskuri: null;
        tapahtumatHeading: null;
        tapahtumatCount: null;
        body: PortableText | null;
        image: ImageWithAlt | null;
        ctaLabel: string | null;
        ctaHref: string | null;
        city: null;
      }
    | {
        _type: "galleria";
        _key: string;
        eyebrow: null;
        heading: string | null;
        count: number | null;
        ottelutHeading: null;
        ottelutCount: null;
        vainMaajoukkue: null;
        seurat: null;
        laskuri: null;
        tapahtumatHeading: null;
        tapahtumatCount: null;
        body: null;
        image: null;
        ctaLabel: null;
        ctaHref: null;
        city: null;
      }
    | {
        _type: "jalkapalloarkisto";
        _key: string;
        eyebrow: null;
        heading: string | null;
        count: null;
        ottelutHeading: null;
        ottelutCount: null;
        vainMaajoukkue: null;
        seurat: null;
        laskuri: null;
        tapahtumatHeading: null;
        tapahtumatCount: null;
        body: string | null;
        image: null;
        ctaLabel: string | null;
        ctaHref: string | null;
        city: null;
      }
    | {
        _type: "otteluohjelma";
        _key: string;
        eyebrow: null;
        heading: null;
        count: null;
        ottelutHeading: string | null;
        ottelutCount: number | null;
        vainMaajoukkue: boolean | null;
        seurat: Array<string> | null;
        laskuri: boolean | null;
        tapahtumatHeading: string | null;
        tapahtumatCount: number | null;
        body: null;
        image: null;
        ctaLabel: null;
        ctaHref: null;
        city: null;
      }
    | {
        _type: "ravintolatSpotlight";
        _key: string;
        eyebrow: string | null;
        heading: string | null;
        count: number | null;
        ottelutHeading: null;
        ottelutCount: null;
        vainMaajoukkue: null;
        seurat: null;
        laskuri: null;
        tapahtumatHeading: null;
        tapahtumatCount: null;
        body: null;
        image: null;
        ctaLabel: null;
        ctaHref: null;
        city: {
          _ref: string;
          name: string | null;
        } | null;
      }
    | {
        _type: "tapahtumat";
        _key: string;
        eyebrow: null;
        heading: string | null;
        count: number | null;
        ottelutHeading: null;
        ottelutCount: null;
        vainMaajoukkue: null;
        seurat: null;
        laskuri: null;
        tapahtumatHeading: null;
        tapahtumatCount: null;
        body: null;
        image: null;
        ctaLabel: null;
        ctaHref: null;
        city: null;
      }
    | {
        _type: "uutiset";
        _key: string;
        eyebrow: string | null;
        heading: string | null;
        count: number | null;
        ottelutHeading: null;
        ottelutCount: null;
        vainMaajoukkue: null;
        seurat: null;
        laskuri: null;
        tapahtumatHeading: null;
        tapahtumatCount: null;
        body: null;
        image: null;
        ctaLabel: null;
        ctaHref: null;
        city: null;
      }
  > | null;
} | null;

// Source: sanity/lib/queries/etusivu.ts
// Variable: etusivuRavintolatQuery
// Query: *[_type == "ravintola" && defined(slug.current) && closed != true    && ($cityId == null || city._ref == $cityId)    && coalesce(ratingOverall, stars, 0) > 0]    | order(coalesce(ratingOverall, stars, 0) desc, name asc)[0...$count]{    _id,    name,    "slug": slug.current,    "city": city->{ name, "slug": slug.current },    stars,    ratingOverall,    priceLevel,    cuisine,    tuomio,    stadionHuomio,    "image": images[0]  }
export type EtusivuRavintolatQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  city: {
    name: string | null;
    slug: string | null;
  } | null;
  stars: number | null;
  ratingOverall: number | null;
  priceLevel: "\u20AC" | "\u20AC\u20AC" | "\u20AC\u20AC\u20AC" | null;
  cuisine: Array<string> | null;
  tuomio: string | null;
  stadionHuomio: string | null;
  image:
    | ({
        _key: string;
      } & ImageWithAlt)
    | null;
}>;

// Source: sanity/lib/queries/etusivu.ts
// Variable: etusivuArkistoQuery
// Query: {    "arvokisat": count(*[_type == "arvokisa" && defined(slug.current)]),    "pelaajat": count(*[_type == "pelaaja" && defined(slug.current)]),    "stadionit": count(*[_type == "stadion" && defined(slug.current)]),    "tilastot": count(*[_type == "jalkapalloTilasto" && defined(slug.current)]),    "fifa": *[_type == "jalkapalloTilasto" && category == "fifa-ranking"      && defined(slug.current)] | order(_updatedAt desc)[0]{      title,      "slug": slug.current,      _updatedAt,      columns[]{ key, label, type },      "rows": rows[0...5]{ cells[]{ key, value } }    }  }
export type EtusivuArkistoQueryResult = {
  arvokisat: number;
  pelaajat: number;
  stadionit: number;
  tilastot: number;
  fifa: {
    title: string | null;
    slug: string | null;
    _updatedAt: string;
    columns: Array<{
      key: string | null;
      label: string | null;
      type: "date" | "link" | "number" | "text" | "year" | null;
    }> | null;
    rows: Array<{
      cells: Array<{
        key: string | null;
        value: string | null;
      }> | null;
    }> | null;
  } | null;
};

// Source: sanity/lib/queries/galleria.ts
// Variable: galleriaAlbumitQuery
// Query: *[_type == "galleriaAlbumi" && defined(slug.current)]    | order(date desc){    _id,    title,    "slug": slug.current,    date,    tiivistelma,    coverImage,    "imageCount": count(images)  }
export type GalleriaAlbumitQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  date: string | null;
  tiivistelma: string | null;
  coverImage: ImageWithAlt | null;
  imageCount: number | null;
}>;

// Source: sanity/lib/queries/galleria.ts
// Variable: etusivuGalleriaQuery
// Query: *[_type == "galleriaAlbumi" && defined(slug.current)]    | order(date desc)[0...$count]{    _id,    title,    "slug": slug.current,    date,    tiivistelma,    coverImage,    "imageCount": count(images)  }
export type EtusivuGalleriaQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  date: string | null;
  tiivistelma: string | null;
  coverImage: ImageWithAlt | null;
  imageCount: number | null;
}>;

// Source: sanity/lib/queries/galleria.ts
// Variable: galleriaAlbumiBySlugQuery
// Query: *[_type == "galleriaAlbumi" && slug.current == $slug][0]{    _id,    _updatedAt,    title,    "slug": slug.current,    date,    tiivistelma,    coverImage,    images,    "event": event->{ title, "slug": slug.current }  }
export type GalleriaAlbumiBySlugQueryResult = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  date: string | null;
  tiivistelma: string | null;
  coverImage: ImageWithAlt | null;
  images: Array<
    {
      _key: string;
    } & ImageWithAlt
  > | null;
  event: {
    title: string | null;
    slug: string | null;
  } | null;
} | null;

// Source: sanity/lib/queries/klubi.ts
// Variable: klubiSivuQuery
// Query: *[_type == "sivu" && slug.current == $slug][0]{    _id,    _updatedAt,    title,    "slug": slug.current,    tiivistelma,    ingress,    hero,    body,    tilastot[]->{      _id,      _updatedAt,      title,      "slug": slug.current,      tiivistelma,      category,      intro,      columns[]{ key, label, type },      rows[]{ cells[]{ key, value } },      lisatiedot,      kuvat[]{ _key, alt, caption, asset, hotspot, crop },      paivitetty,      jarjestys,      "sources": coalesce(sources, [])    },    seoTitle,    seoDescription  }
export type KlubiSivuQueryResult = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  tiivistelma: string | null;
  ingress: string | null;
  hero: ImageWithAlt | null;
  body: PortableText | null;
  tilastot: Array<{
    _id: string;
    _updatedAt: string;
    title: string | null;
    slug: string | null;
    tiivistelma: string | null;
    category:
      | "arvokisa"
      | "ballon-dor"
      | "champions"
      | "conference-league"
      | "eurocup"
      | "fifa-ranking"
      | "huuhkajat"
      | "intercontinental"
      | "karsinta"
      | "klubi"
      | "lupaavat"
      | "muu"
      | "palloliitto"
      | "pelaaja"
      | "saavutukset"
      | "super-cup"
      | "uefa-cup"
      | "ulkomaiset-mestarit"
      | "valmentajat"
      | "valmentajien-palkat"
      | "vuoden-pelaaja"
      | null;
    intro: PortableText | null;
    columns: Array<{
      key: string | null;
      label: string | null;
      type: "date" | "link" | "number" | "text" | "year" | null;
    }> | null;
    rows: Array<{
      cells: Array<{
        key: string | null;
        value: string | null;
      }> | null;
    }> | null;
    lisatiedot: PortableText | null;
    kuvat: Array<{
      _key: string;
      alt: string | null;
      caption: string | null;
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    }> | null;
    paivitetty: string | null;
    jarjestys: number | null;
    sources: Array<string> | Array<never>;
  }> | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: sanity/lib/queries/klubi.ts
// Variable: klubiToimintaListQuery
// Query: *[_type == "klubiToiminta" && defined(slug.current)]    | order(jarjestys asc, title asc){    _id,    title,    "slug": slug.current,    tiivistelma,    "kuva": kuvat[0],    "vuosiMaara": count(vuodet),    "uusinVuosi": math::max(vuodet[].vuosi)  }
export type KlubiToimintaListQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  tiivistelma: string | null;
  kuva:
    | ({
        _key: string;
      } & ImageWithAlt)
    | null;
  vuosiMaara: number | null;
  uusinVuosi: number | null;
}>;

// Source: sanity/lib/queries/klubi.ts
// Variable: klubiToimintaBySlugQuery
// Query: *[_type == "klubiToiminta" && slug.current == $slug][0]{    _id,    _updatedAt,    title,    "slug": slug.current,    tiivistelma,    kuvaus,    kuvat,    seoTitle,    seoDescription,    "vuodet": vuodet[] | order(vuosi desc, paivamaara desc){      _key,      vuosi,      paivamaara,      otsikko,      jarjestysnumero,      osallistujat,      paikka,      kuvaus,      linkki{ url, teksti },      kuvat    },    tilastot[]->{      _id,      _updatedAt,      title,      "slug": slug.current,      tiivistelma,      category,      intro,      columns[]{ key, label, type },      rows[]{ cells[]{ key, value } },      lisatiedot,      kuvat[]{ _key, alt, caption, asset, hotspot, crop },      paivitetty,      jarjestys,      "sources": coalesce(sources, [])    }  }
export type KlubiToimintaBySlugQueryResult = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  tiivistelma: string | null;
  kuvaus: PortableText | null;
  kuvat: Array<
    {
      _key: string;
    } & ImageWithAlt
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
  vuodet: Array<{
    _key: string;
    vuosi: number | null;
    paivamaara: string | null;
    otsikko: string | null;
    jarjestysnumero: number | null;
    osallistujat: Array<string> | null;
    paikka: string | null;
    kuvaus: string | null;
    linkki: {
      url: string | null;
      teksti: string | null;
    } | null;
    kuvat: Array<
      {
        _key: string;
      } & ImageWithAlt
    > | null;
  }> | null;
  tilastot: Array<{
    _id: string;
    _updatedAt: string;
    title: string | null;
    slug: string | null;
    tiivistelma: string | null;
    category:
      | "arvokisa"
      | "ballon-dor"
      | "champions"
      | "conference-league"
      | "eurocup"
      | "fifa-ranking"
      | "huuhkajat"
      | "intercontinental"
      | "karsinta"
      | "klubi"
      | "lupaavat"
      | "muu"
      | "palloliitto"
      | "pelaaja"
      | "saavutukset"
      | "super-cup"
      | "uefa-cup"
      | "ulkomaiset-mestarit"
      | "valmentajat"
      | "valmentajien-palkat"
      | "vuoden-pelaaja"
      | null;
    intro: PortableText | null;
    columns: Array<{
      key: string | null;
      label: string | null;
      type: "date" | "link" | "number" | "text" | "year" | null;
    }> | null;
    rows: Array<{
      cells: Array<{
        key: string | null;
        value: string | null;
      }> | null;
    }> | null;
    lisatiedot: PortableText | null;
    kuvat: Array<{
      _key: string;
      alt: string | null;
      caption: string | null;
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    }> | null;
    paivitetty: string | null;
    jarjestys: number | null;
    sources: Array<string> | Array<never>;
  }> | null;
} | null;

// Source: sanity/lib/queries/klubi.ts
// Variable: klubiToimintaSiblingsQuery
// Query: *[_type == "klubiToiminta" && defined(slug.current) && slug.current != $slug]    | order(jarjestys asc, title asc)[0...4]{    _id,    title,    "slug": slug.current,    tiivistelma  }
export type KlubiToimintaSiblingsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  tiivistelma: string | null;
}>;

// Source: sanity/lib/queries/klubi.ts
// Variable: klubiToimintaSlugsQuery
// Query: *[_type == "klubiToiminta" && defined(slug.current)][].slug.current
export type KlubiToimintaSlugsQueryResult = Array<string | null>;

// Source: sanity/lib/queries/klubi.ts
// Variable: hallitusListQuery
// Query: *[_type == "hallitusJasen"] | order(order asc, name asc){    _id,    name,    role,    image,    bio,    email,    phone  }
export type HallitusListQueryResult = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  image: ImageWithAlt | null;
  bio: string | null;
  email: string | null;
  phone: string | null;
}>;

// Source: sanity/lib/queries/kommentit.ts
// Variable: kommentitQuery
// Query: *[_type == "kommentti" && uutinen._ref == $uutinenId && piilotettu != true]    | order(lahetetty asc){      _id,      nimi,      teksti,      veikkaus{ jarjestys, maalikuningas },      lahetetty,      lahde    }
export type KommentitQueryResult = Array<{
  _id: string;
  nimi: string | null;
  teksti: string | null;
  veikkaus: {
    jarjestys: Array<string> | null;
    maalikuningas: string | null;
  } | null;
  lahetetty: string | null;
  lahde: "blogspot" | "sivusto" | null;
}>;

// Source: sanity/lib/queries/ottelut.ts
// Variable: tulevatOttelutQuery
// Query: *[_type == "ottelu" && defined(aika) && dateTime(aika) > dateTime(now()) - 60*60*24]    | order(aika asc){    _id,    aika,    koti,    vieras,    kilpailu,    stadion,    klubiPaikalla,    vierasmatka  }
export type TulevatOttelutQueryResult = Array<{
  _id: string;
  aika: string | null;
  koti: string | null;
  vieras: string | null;
  kilpailu: string | null;
  stadion: string | null;
  klubiPaikalla: boolean | null;
  vierasmatka: boolean | null;
}>;

// Source: sanity/lib/queries/ravintolat.ts
// Variable: ravintolatCountQuery
// Query: count(*[  _type == "ravintola" && defined(slug.current)  && ($citySlug == null || city->slug.current == $citySlug)  && ($countryNames == null || city->country in $countryNames)  && ($maakuntaSlugs == null      || (city->country == "Suomi" && city->maakunta in $maakuntaSlugs))  && ($cuisine == null || $cuisine in cuisine)  && ($minRating == null || coalesce(ratingOverall, stars, 0) >= $minRating)  && ($includeClosed == true || closed != true)])
export type RavintolatCountQueryResult = number;

// Source: sanity/lib/queries/ravintolat.ts
// Variable: ravintolatFacetsQuery
// Query: {  "places": *[_type == "kaupunki" && defined(slug.current)      && count(*[_type == "ravintola" && references(^._id)]) > 0]    | order(name asc){      name,      "slug": slug.current,      country,      maakunta,      "count": count(*[_type == "ravintola" && references(^._id) && closed != true])    },  "cuisines": array::unique(*[_type == "ravintola" && defined(cuisine)].cuisine[]),  "total": count(*[_type == "ravintola" && defined(slug.current) && closed != true]),  "closedCount": count(*[_type == "ravintola" && closed == true]),  "firstVisitYear": *[_type == "ravintola" && defined(visitedAt)]    | order(visitedAt asc)[0].visitedAt}
export type RavintolatFacetsQueryResult = {
  places: Array<{
    name: string | null;
    slug: string | null;
    country: string | null;
    maakunta:
      | "ahvenanmaa"
      | "etela-karjala"
      | "etela-pohjanmaa"
      | "etela-savo"
      | "kainuu"
      | "kanta-hame"
      | "keski-pohjanmaa"
      | "keski-suomi"
      | "kymenlaakso"
      | "lappi"
      | "paijat-hame"
      | "pirkanmaa"
      | "pohjanmaa"
      | "pohjois-karjala"
      | "pohjois-pohjanmaa"
      | "pohjois-savo"
      | "satakunta"
      | "uusimaa"
      | "varsinais-suomi"
      | null;
    count: number;
  }>;
  cuisines: Array<string>;
  total: number;
  closedCount: number;
  firstVisitYear: string | null;
};

// Source: sanity/lib/queries/ravintolat.ts
// Variable: ravintolaBySlugQuery
// Query: *[_type == "ravintola" && slug.current == $slug][0]{      _id,  name,  "slug": slug.current,  "city": city->{ name, "slug": slug.current, country },  stars,  ratingOverall,  ratingFood,  ratingPrice,  ratingAtmosphere,  priceLevel,  cuisine,  closed,  tiivistelma,  tuomio,  stadionHuomio,  "image": images[0],    _updatedAt,    address,    postalCode,    phone,    website,    location,    closedNote,    pros,    cons,    visitedAt,    visits,    visitContext,    review,    ottelupaivana,    images,    seoTitle,    seoDescription,    "userReviews": *[_type == "ravintolaKayttajaArvostelu"      && restaurant._ref == ^._id]      | order(submittedAt desc){        _id,        reviewerName,        stars,        comment,        submittedAt      },    "related": *[_type == "ravintola" && defined(slug.current)      && _id != ^._id && closed != true && city._ref == ^.city._ref]      | order(coalesce(ratingOverall, stars, 0) desc, name asc)[0...3]{  _id,  name,  "slug": slug.current,  "city": city->{ name, "slug": slug.current, country },  stars,  ratingOverall,  ratingFood,  ratingPrice,  ratingAtmosphere,  priceLevel,  cuisine,  closed,  tiivistelma,  tuomio,  stadionHuomio,  "image": images[0]}  }
export type RavintolaBySlugQueryResult = {
  _id: string;
  name: string | null;
  slug: string | null;
  city: {
    name: string | null;
    slug: string | null;
    country: string | null;
  } | null;
  stars: number | null;
  ratingOverall: number | null;
  ratingFood: number | null;
  ratingPrice: number | null;
  ratingAtmosphere: number | null;
  priceLevel: "\u20AC" | "\u20AC\u20AC" | "\u20AC\u20AC\u20AC" | null;
  cuisine: Array<string> | null;
  closed: boolean | null;
  tiivistelma: string | null;
  tuomio: string | null;
  stadionHuomio: string | null;
  image:
    | ({
        _key: string;
      } & ImageWithAlt)
    | null;
  _updatedAt: string;
  address: string | null;
  postalCode: string | null;
  phone: string | null;
  website: string | null;
  location: Geopoint | null;
  closedNote: string | null;
  pros: Array<string> | null;
  cons: Array<string> | null;
  visitedAt: string | null;
  visits: Array<string> | null;
  visitContext: string | null;
  review: PortableText | null;
  ottelupaivana: string | null;
  images: Array<
    {
      _key: string;
    } & ImageWithAlt
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
  userReviews: Array<{
    _id: string;
    reviewerName: string | null;
    stars: number | null;
    comment: string | null;
    submittedAt: string | null;
  }>;
  related: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    city: {
      name: string | null;
      slug: string | null;
      country: string | null;
    } | null;
    stars: number | null;
    ratingOverall: number | null;
    ratingFood: number | null;
    ratingPrice: number | null;
    ratingAtmosphere: number | null;
    priceLevel: "\u20AC" | "\u20AC\u20AC" | "\u20AC\u20AC\u20AC" | null;
    cuisine: Array<string> | null;
    closed: boolean | null;
    tiivistelma: string | null;
    tuomio: string | null;
    stadionHuomio: string | null;
    image:
      | ({
          _key: string;
        } & ImageWithAlt)
      | null;
  }>;
} | null;

// Source: sanity/lib/queries/ravintolat.ts
// Variable: ravintolaSlugsQuery
// Query: *[_type == "ravintola" && defined(slug.current)].slug.current
export type RavintolaSlugsQueryResult = Array<string | null>;

// Source: sanity/lib/queries/ravintolat.ts
// Variable: ravintolaOptionsQuery
// Query: *[_type == "ravintola" && defined(slug.current)] | order(name asc){    _id,    name,    "slug": slug.current,    "city": city->name  }
export type RavintolaOptionsQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  city: string | null;
}>;

// Source: sanity/lib/queries/sitemap.ts
// Variable: sitemapByTypeQuery
// Query: *[_type == $type && defined(slug.current)] | order(_updatedAt desc) {    "slug": slug.current,    "updatedAt": _updatedAt  }
export type SitemapByTypeQueryResult = Array<{
  slug: string | null;
  updatedAt: string;
}>;

// Source: sanity/lib/queries/sitemap.ts
// Variable: sitemapTilastotQuery
// Query: *[_type == "jalkapalloTilasto" && defined(slug.current)] | order(_updatedAt desc) {    _id,    _type,    "slug": slug.current,    category,    huuhkajatOsio,    "parent": *[      _type in ["arvokisa", "pelaaja", "klubiToiminta", "sivu"]      && references(^._id)      && !(_id in path("drafts.**"))    ] | order(_type asc, _id asc)[0]{ _type, "slug": slug.current },    "updatedAt": _updatedAt  }
export type SitemapTilastotQueryResult = Array<{
  _id: string;
  _type: "jalkapalloTilasto";
  slug: string | null;
  category:
    | "arvokisa"
    | "ballon-dor"
    | "champions"
    | "conference-league"
    | "eurocup"
    | "fifa-ranking"
    | "huuhkajat"
    | "intercontinental"
    | "karsinta"
    | "klubi"
    | "lupaavat"
    | "muu"
    | "palloliitto"
    | "pelaaja"
    | "saavutukset"
    | "super-cup"
    | "uefa-cup"
    | "ulkomaiset-mestarit"
    | "valmentajat"
    | "valmentajien-palkat"
    | "vuoden-pelaaja"
    | null;
  huuhkajatOsio:
    | "avauskokoonpano"
    | "englanti"
    | "huuhkaja-arvostelu"
    | "kansojen-liiga"
    | "muut"
    | "pelaajatilastot"
    | null;
  parent:
    | {
        _type: "arvokisa";
        slug: string | null;
      }
    | {
        _type: "klubiToiminta";
        slug: string | null;
      }
    | {
        _type: "pelaaja";
        slug: string | null;
      }
    | {
        _type: "sivu";
        slug: string | null;
      }
    | null;
  updatedAt: string;
}>;

// Source: sanity/lib/queries/sitemap.ts
// Variable: sitemapArchiveYearsQuery
// Query: *[_type == "uutinen" && defined(publishedAt)]    | order(publishedAt desc) {      "slug": string::split(publishedAt, "-")[0],      "updatedAt": _updatedAt    }
export type SitemapArchiveYearsQueryResult = Array<{
  slug: string | null;
  updatedAt: string;
}>;

// Source: sanity/lib/queries/uutiset.ts
// Variable: uutisetPageQuery
// Query: {    "items": *[_type == "uutinen" && defined(slug.current) && ($category == null || $category in categories)] | order(publishedAt desc)[$start...$end]{      _id,      title,      "slug": slug.current,      publishedAt,      excerpt,      tiivistelma,      coverImage,      categories    },    "total": count(*[_type == "uutinen" && defined(slug.current) && ($category == null || $category in categories)])  }
export type UutisetPageQueryResult = {
  items: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    publishedAt: string | null;
    excerpt: string | null;
    tiivistelma: string | null;
    coverImage: ImageWithAlt | null;
    categories: Array<string> | null;
  }>;
  total: number;
};

// Source: sanity/lib/queries/uutiset.ts
// Variable: uutisetCategoriesQuery
// Query: array::unique(*[_type == "uutinen" && defined(slug.current)].categories[])
export type UutisetCategoriesQueryResult = Array<string | null>;

// Source: sanity/lib/queries/uutiset.ts
// Variable: uutinenSlugsQuery
// Query: *[_type == "uutinen" && defined(slug.current)].slug.current
export type UutinenSlugsQueryResult = Array<string | null>;

// Source: sanity/lib/queries/uutiset.ts
// Variable: uutinenDetailQuery
// Query: *[_type == "uutinen" && defined(slug.current) && slug.current == $slug][0]{      _id,      title,      "slug": slug.current,      publishedAt,      excerpt,      tiivistelma,      coverImage,      categories,    _updatedAt,    body,    lahde{ nimi, url, pvm },    ulkoinenLinkki,    "author": author->{ name, role },    kommentointi{ kaytossa, tyyppi, sulkeutuu, vaihtoehdot, sijoituksia, maalikuningas, ohje },    seoTitle,    seoDescription  }
export type UutinenDetailQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  tiivistelma: string | null;
  coverImage: ImageWithAlt | null;
  categories: Array<string> | null;
  _updatedAt: string;
  body: PortableText | null;
  lahde: {
    nimi: string | null;
    url: string | null;
    pvm: string | null;
  } | null;
  ulkoinenLinkki: string | null;
  author: {
    name: string | null;
    role: string | null;
  } | null;
  kommentointi: {
    kaytossa: boolean | null;
    tyyppi: "kommentti" | "sarjajarjestys" | "voittajaveikkaus" | null;
    sulkeutuu: string | null;
    vaihtoehdot: Array<string> | null;
    sijoituksia: number | null;
    maalikuningas: boolean | null;
    ohje: string | null;
  } | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: sanity/lib/queries/uutiset.ts
// Variable: relatedUutisetQuery
// Query: *[_type == "uutinen" && defined(slug.current) && slug.current != $slug    && count((categories[])[@ in $categories]) > 0]    | order(publishedAt desc)[0...$count]{      _id,      title,      "slug": slug.current,      publishedAt,      excerpt,      tiivistelma,      coverImage,      categories  }
export type RelatedUutisetQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  tiivistelma: string | null;
  coverImage: ImageWithAlt | null;
  categories: Array<string> | null;
}>;

// Source: sanity/lib/queries/uutiset.ts
// Variable: uutisetArchiveYearsQuery
// Query: *[_type == "uutinen" && defined(slug.current) && defined(publishedAt)]{    "year": string::split(publishedAt, "-")[0]  }
export type UutisetArchiveYearsQueryResult = Array<{
  year: string | null;
}>;

// Source: sanity/lib/queries/uutiset.ts
// Variable: uutisetByYearQuery
// Query: {    "items": *[_type == "uutinen" && defined(slug.current) && publishedAt >= $from && publishedAt < $to]      | order(publishedAt desc)[$start...$end]{      _id,      title,      "slug": slug.current,      publishedAt,      excerpt,      tiivistelma,      coverImage,      categories    },    "total": count(*[_type == "uutinen" && defined(slug.current) && publishedAt >= $from && publishedAt < $to])  }
export type UutisetByYearQueryResult = {
  items: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    publishedAt: string | null;
    excerpt: string | null;
    tiivistelma: string | null;
    coverImage: ImageWithAlt | null;
    categories: Array<string> | null;
  }>;
  total: number;
};

// Source: sanity/lib/queries/uutiset.ts
// Variable: tulevatTapahtumatQuery
// Query: *[_type == "tapahtuma" && defined(slug.current) && startsAt >= now()] | order(startsAt asc){      _id,      title,      "slug": slug.current,      startsAt,      endsAt,      location,      tiivistelma,      juhla,      image  }
export type TulevatTapahtumatQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  startsAt: string | null;
  endsAt: string | null;
  location: string | null;
  tiivistelma: string | null;
  juhla: boolean | null;
  image: ImageWithAlt | null;
}>;

// Source: sanity/lib/queries/uutiset.ts
// Variable: menneetTapahtumatQuery
// Query: *[_type == "tapahtuma" && defined(slug.current) && startsAt < now()] | order(startsAt desc){      _id,      title,      "slug": slug.current,      startsAt,      endsAt,      location,      tiivistelma,      juhla,      image  }
export type MenneetTapahtumatQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  startsAt: string | null;
  endsAt: string | null;
  location: string | null;
  tiivistelma: string | null;
  juhla: boolean | null;
  image: ImageWithAlt | null;
}>;

// Source: sanity/lib/queries/uutiset.ts
// Variable: tapahtumaSlugsQuery
// Query: *[_type == "tapahtuma" && defined(slug.current)].slug.current
export type TapahtumaSlugsQueryResult = Array<string | null>;

// Source: sanity/lib/queries/uutiset.ts
// Variable: tapahtumaDetailQuery
// Query: *[_type == "tapahtuma" && defined(slug.current) && slug.current == $slug][0]{      _id,      title,      "slug": slug.current,      startsAt,      endsAt,      location,      tiivistelma,      juhla,      image,    _updatedAt,    description,    signupUrl,    signupEmail,    seoTitle,    seoDescription  }
export type TapahtumaDetailQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  startsAt: string | null;
  endsAt: string | null;
  location: string | null;
  tiivistelma: string | null;
  juhla: boolean | null;
  image: ImageWithAlt | null;
  _updatedAt: string;
  description: PortableText | null;
  signupUrl: string | null;
  signupEmail: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "arvokisa" && defined(slug.current)] | order(vuosi desc, title asc){\n    _id,\n    title,\n    "slug": slug.current,\n    tiivistelma,\n    kisatyyppi,\n    vuosi,\n    isantamaat,\n    voittaja,\n    suomenSijoitus\n  }\n': ArvokisatListQueryResult;
    '\n  *[_type == "arvokisa" && defined(slug.current)][].slug.current\n': ArvokisaSlugsQueryResult;
    '\n  *[_type == "arvokisa" && slug.current == $slug][0]{\n    _id,\n    _updatedAt,\n    title,\n    "slug": slug.current,\n    tiivistelma,\n    kisatyyppi,\n    vuosi,\n    isantamaat,\n    voittaja,\n    suomenSijoitus,\n    alkuPvm,\n    loppuPvm,\n    hopea,\n    pronssi,\n    kuvaus,\n    tilastot[]->{\n      _id,\n      _updatedAt,\n      title,\n      "slug": slug.current,\n      tiivistelma,\n      category,\n      intro,\n      columns[]{ key, label, type },\n      rows[]{ cells[]{ key, value } },\n      lisatiedot,\n      kuvat[]{ _key, alt, caption, asset, hotspot, crop },\n      paivitetty,\n      jarjestys,\n      "sources": coalesce(sources, [])\n    },\n    kuvat[]{ _key, alt, caption, asset, hotspot, crop },\n    seoTitle,\n    seoDescription\n  }\n': ArvokisaBySlugQueryResult;
    '\n  *[\n    _type == "jalkapalloTilasto"\n    && category == "arvokisa"\n    && count(*[_type == "arvokisa" && references(^._id)]) == 0\n  ] | order(coalesce(jarjestys, 1000) asc, title asc){\n    _id,\n      _updatedAt,\n      title,\n      "slug": slug.current,\n      tiivistelma,\n      category,\n      intro,\n      columns[]{ key, label, type },\n      rows[]{ cells[]{ key, value } },\n      lisatiedot,\n      kuvat[]{ _key, alt, caption, asset, hotspot, crop },\n      paivitetty,\n      jarjestys,\n      "sources": coalesce(sources, [])\n  }\n': ArvokisaMitalitaulukotQueryResult;
    '\n  *[_type == "arvokisa" && defined(slug.current)\n    && slug.current != $slug\n    && kisatyyppi == $kisatyyppi] | order(vuosi desc)[0...4]{\n    _id,\n    title,\n    "slug": slug.current,\n    tiivistelma,\n    kisatyyppi,\n    vuosi,\n    isantamaat,\n    voittaja,\n    suomenSijoitus\n  }\n': ArvokisatRelatedQueryResult;
    '\n  *[_type == "pelaaja" && defined(slug.current)] | order(name asc){\n    _id,\n    name,\n    "slug": slug.current,\n    tiivistelma,\n    pelipaikka,\n    maaottelut,\n    maalit,\n    "kuva": kuvat[0]{ alt, caption, asset, hotspot, crop }\n  }\n': PelaajatListQueryResult;
    '\n  *[_type == "pelaaja" && defined(slug.current)][].slug.current\n': PelaajaSlugsQueryResult;
    '\n  *[_type == "pelaaja" && slug.current == $slug][0]{\n    _id,\n    _updatedAt,\n    name,\n    "slug": slug.current,\n    tiivistelma,\n    pelipaikka,\n    maaottelut,\n    maalit,\n    syntymaaika,\n    seurat[]{ _key, seura, alkuvuosi, loppuvuosi },\n    kuvaus,\n    tilastot[]->{\n      _id,\n      _updatedAt,\n      title,\n      "slug": slug.current,\n      tiivistelma,\n      category,\n      intro,\n      columns[]{ key, label, type },\n      rows[]{ cells[]{ key, value } },\n      lisatiedot,\n      kuvat[]{ _key, alt, caption, asset, hotspot, crop },\n      paivitetty,\n      jarjestys,\n      "sources": coalesce(sources, [])\n    },\n    kuvat[]{ _key, alt, caption, asset, hotspot, crop },\n    seoTitle,\n    seoDescription\n  }\n': PelaajaBySlugQueryResult;
    '\n  *[_type == "pelaaja" && defined(slug.current) && slug.current != $slug]\n    | order(coalesce(maaottelut, 0) desc, name asc)[0...4]{\n    _id,\n    name,\n    "slug": slug.current,\n    tiivistelma,\n    pelipaikka,\n    maaottelut,\n    maalit,\n    "kuva": kuvat[0]{ alt, caption, asset, hotspot, crop }\n  }\n': PelaajatRelatedQueryResult;
    '\n  *[_type == "stadion" && defined(slug.current)]\n    | order(city->country asc, name asc){\n    _id,\n    name,\n    "slug": slug.current,\n    tiivistelma,\n    capacity,\n    openedYear,\n    "city": city->{ name, "slug": slug.current, country },\n    "kuva": images[0]{ alt, caption, asset, hotspot, crop }\n  }\n': StadionitListQueryResult;
    '\n  *[_type == "stadion" && defined(slug.current)][].slug.current\n': StadionSlugsQueryResult;
    '\n  *[_type == "stadion" && slug.current == $slug][0]{\n    _id,\n    _updatedAt,\n    name,\n    "slug": slug.current,\n    tiivistelma,\n    capacity,\n    openedYear,\n    address,\n    "city": city->{ name, "slug": slug.current, country },\n    location{ lat, lng, alt },\n    description,\n    images[]{ _key, alt, caption, asset, hotspot, crop },\n    seoTitle,\n    seoDescription\n  }\n': StadionBySlugQueryResult;
    '\n  *[_type == "stadion" && defined(slug.current) && slug.current != $slug]\n    | order(select(city->name == $cityName => 0, 1) asc, name asc)[0...4]{\n    _id,\n    name,\n    "slug": slug.current,\n    tiivistelma,\n    capacity,\n    openedYear,\n    "city": city->{ name, "slug": slug.current, country },\n    "kuva": images[0]{ alt, caption, asset, hotspot, crop }\n  }\n': StadionitRelatedQueryResult;
    '\n  *[_type == "jalkapalloTilasto" && category == $category]\n    | order(coalesce(jarjestys, 1000) asc, title asc){\n    \n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  tiivistelma,\n  category,\n  huuhkajatOsio,\n  intro,\n  columns[]{ key, label, type },\n  rows[]{ cells[]{ key, value } },\n  lisatiedot,\n  kuvat[]{ _key, alt, caption, asset, hotspot, crop },\n  paivitetty,\n  jarjestys,\n  "sources": coalesce(sources, [])\n\n  }\n': TilastotByCategoryQueryResult;
    '\n  *[_type == "jalkapalloTilasto" && category in $categories]\n    | order(coalesce(jarjestys, 1000) asc, title asc){\n    \n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  tiivistelma,\n  category,\n  huuhkajatOsio,\n  intro,\n  columns[]{ key, label, type },\n  rows[]{ cells[]{ key, value } },\n  lisatiedot,\n  kuvat[]{ _key, alt, caption, asset, hotspot, crop },\n  paivitetty,\n  jarjestys,\n  "sources": coalesce(sources, [])\n\n  }\n': TilastotByCategoriesQueryResult;
    '\n  *[\n    _type == "jalkapalloTilasto"\n    && category == $category\n    && slug.current == $slug\n  ][0]{\n    \n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  tiivistelma,\n  category,\n  huuhkajatOsio,\n  intro,\n  columns[]{ key, label, type },\n  rows[]{ cells[]{ key, value } },\n  lisatiedot,\n  kuvat[]{ _key, alt, caption, asset, hotspot, crop },\n  paivitetty,\n  jarjestys,\n  "sources": coalesce(sources, [])\n\n  }\n': TilastoBySlugQueryResult;
    '\n  *[\n    _type == "jalkapalloTilasto"\n    && category == $category\n    && defined(slug.current)\n  ].slug.current\n': TilastoSlugsByCategoryQueryResult;
    '{\n  "taulukot": *[_type == "jalkapalloTilasto" && category == "huuhkajat"]\n    | order(coalesce(jarjestys, 1000) asc, title asc){ \n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  tiivistelma,\n  huuhkajatOsio\n },\n  "karsinnat": *[\n    _type == "jalkapalloTilasto" && category == "karsinta" && defined(slug.current)\n  ] | order(coalesce(jarjestys, 1000) asc, title asc){ \n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  tiivistelma,\n  huuhkajatOsio\n }\n}': HuuhkajatHubQueryResult;
    '\n  *[\n    _type == "jalkapalloTilasto"\n    && category == "huuhkajat"\n    && select(\n      $osio == $oletus => !(huuhkajatOsio in $tunnetut),\n      huuhkajatOsio == $osio\n    )\n  ] | order(coalesce(jarjestys, 1000) asc, title asc){\n    \n  _id,\n  _updatedAt,\n  title,\n  "slug": slug.current,\n  tiivistelma,\n  category,\n  huuhkajatOsio,\n  intro,\n  columns[]{ key, label, type },\n  rows[]{ cells[]{ key, value } },\n  lisatiedot,\n  kuvat[]{ _key, alt, caption, asset, hotspot, crop },\n  paivitetty,\n  jarjestys,\n  "sources": coalesce(sources, [])\n\n  }\n': HuuhkajatOsioQueryResult;
    '\n  *[_type == "jalkapalloTilasto" && defined(category)]{\n    category,\n    "updatedAt": _updatedAt\n  }\n': ArkistoSummaryQueryResult;
    '\n  *[_type == "etusivu"][0]{\n    heroEyebrow,\n    heroTitle,\n    heroDescription,\n    heroImage,\n    heroCtas[]{ label, href, primary },\n    seuraavaOttelu{ ottelu, kilpailu, aika },\n    blocks[]{\n      _type,\n      _key,\n      eyebrow,\n      heading,\n      count,\n      ottelutHeading,\n      ottelutCount,\n      vainMaajoukkue,\n      seurat,\n      laskuri,\n      tapahtumatHeading,\n      tapahtumatCount,\n      body,\n      image,\n      ctaLabel,\n      ctaHref,\n      "city": city->{ "_ref": _id, name }\n    }\n  }\n': EtusivuQueryResult;
    '\n  *[_type == "ravintola" && defined(slug.current) && closed != true\n    && ($cityId == null || city._ref == $cityId)\n    && coalesce(ratingOverall, stars, 0) > 0]\n    | order(coalesce(ratingOverall, stars, 0) desc, name asc)[0...$count]{\n    _id,\n    name,\n    "slug": slug.current,\n    "city": city->{ name, "slug": slug.current },\n    stars,\n    ratingOverall,\n    priceLevel,\n    cuisine,\n    tuomio,\n    stadionHuomio,\n    "image": images[0]\n  }\n': EtusivuRavintolatQueryResult;
    '\n  {\n    "arvokisat": count(*[_type == "arvokisa" && defined(slug.current)]),\n    "pelaajat": count(*[_type == "pelaaja" && defined(slug.current)]),\n    "stadionit": count(*[_type == "stadion" && defined(slug.current)]),\n    "tilastot": count(*[_type == "jalkapalloTilasto" && defined(slug.current)]),\n    "fifa": *[_type == "jalkapalloTilasto" && category == "fifa-ranking"\n      && defined(slug.current)] | order(_updatedAt desc)[0]{\n      title,\n      "slug": slug.current,\n      _updatedAt,\n      columns[]{ key, label, type },\n      "rows": rows[0...5]{ cells[]{ key, value } }\n    }\n  }\n': EtusivuArkistoQueryResult;
    '\n  *[_type == "galleriaAlbumi" && defined(slug.current)]\n    | order(date desc){\n    _id,\n    title,\n    "slug": slug.current,\n    date,\n    tiivistelma,\n    coverImage,\n    "imageCount": count(images)\n  }\n': GalleriaAlbumitQueryResult;
    '\n  *[_type == "galleriaAlbumi" && defined(slug.current)]\n    | order(date desc)[0...$count]{\n    _id,\n    title,\n    "slug": slug.current,\n    date,\n    tiivistelma,\n    coverImage,\n    "imageCount": count(images)\n  }\n': EtusivuGalleriaQueryResult;
    '\n  *[_type == "galleriaAlbumi" && slug.current == $slug][0]{\n    _id,\n    _updatedAt,\n    title,\n    "slug": slug.current,\n    date,\n    tiivistelma,\n    coverImage,\n    images,\n    "event": event->{ title, "slug": slug.current }\n  }\n': GalleriaAlbumiBySlugQueryResult;
    '\n  *[_type == "sivu" && slug.current == $slug][0]{\n    _id,\n    _updatedAt,\n    title,\n    "slug": slug.current,\n    tiivistelma,\n    ingress,\n    hero,\n    body,\n    tilastot[]->{\n      _id,\n      _updatedAt,\n      title,\n      "slug": slug.current,\n      tiivistelma,\n      category,\n      intro,\n      columns[]{ key, label, type },\n      rows[]{ cells[]{ key, value } },\n      lisatiedot,\n      kuvat[]{ _key, alt, caption, asset, hotspot, crop },\n      paivitetty,\n      jarjestys,\n      "sources": coalesce(sources, [])\n    },\n    seoTitle,\n    seoDescription\n  }\n': KlubiSivuQueryResult;
    '\n  *[_type == "klubiToiminta" && defined(slug.current)]\n    | order(jarjestys asc, title asc){\n    _id,\n    title,\n    "slug": slug.current,\n    tiivistelma,\n    "kuva": kuvat[0],\n    "vuosiMaara": count(vuodet),\n    "uusinVuosi": math::max(vuodet[].vuosi)\n  }\n': KlubiToimintaListQueryResult;
    '\n  *[_type == "klubiToiminta" && slug.current == $slug][0]{\n    _id,\n    _updatedAt,\n    title,\n    "slug": slug.current,\n    tiivistelma,\n    kuvaus,\n    kuvat,\n    seoTitle,\n    seoDescription,\n    "vuodet": vuodet[] | order(vuosi desc, paivamaara desc){\n      _key,\n      vuosi,\n      paivamaara,\n      otsikko,\n      jarjestysnumero,\n      osallistujat,\n      paikka,\n      kuvaus,\n      linkki{ url, teksti },\n      kuvat\n    },\n    tilastot[]->{\n      _id,\n      _updatedAt,\n      title,\n      "slug": slug.current,\n      tiivistelma,\n      category,\n      intro,\n      columns[]{ key, label, type },\n      rows[]{ cells[]{ key, value } },\n      lisatiedot,\n      kuvat[]{ _key, alt, caption, asset, hotspot, crop },\n      paivitetty,\n      jarjestys,\n      "sources": coalesce(sources, [])\n    }\n  }\n': KlubiToimintaBySlugQueryResult;
    '\n  *[_type == "klubiToiminta" && defined(slug.current) && slug.current != $slug]\n    | order(jarjestys asc, title asc)[0...4]{\n    _id,\n    title,\n    "slug": slug.current,\n    tiivistelma\n  }\n': KlubiToimintaSiblingsQueryResult;
    '\n  *[_type == "klubiToiminta" && defined(slug.current)][].slug.current\n': KlubiToimintaSlugsQueryResult;
    '\n  *[_type == "hallitusJasen"] | order(order asc, name asc){\n    _id,\n    name,\n    role,\n    image,\n    bio,\n    email,\n    phone\n  }\n': HallitusListQueryResult;
    '\n  *[_type == "kommentti" && uutinen._ref == $uutinenId && piilotettu != true]\n    | order(lahetetty asc){\n      _id,\n      nimi,\n      teksti,\n      veikkaus{ jarjestys, maalikuningas },\n      lahetetty,\n      lahde\n    }\n': KommentitQueryResult;
    '\n  *[_type == "ottelu" && defined(aika) && dateTime(aika) > dateTime(now()) - 60*60*24]\n    | order(aika asc){\n    _id,\n    aika,\n    koti,\n    vieras,\n    kilpailu,\n    stadion,\n    klubiPaikalla,\n    vierasmatka\n  }\n': TulevatOttelutQueryResult;
    '\n  count(*[\n  _type == "ravintola" && defined(slug.current)\n  && ($citySlug == null || city->slug.current == $citySlug)\n  && ($countryNames == null || city->country in $countryNames)\n  && ($maakuntaSlugs == null\n      || (city->country == "Suomi" && city->maakunta in $maakuntaSlugs))\n  && ($cuisine == null || $cuisine in cuisine)\n  && ($minRating == null || coalesce(ratingOverall, stars, 0) >= $minRating)\n  && ($includeClosed == true || closed != true)\n])\n': RavintolatCountQueryResult;
    '{\n  "places": *[_type == "kaupunki" && defined(slug.current)\n      && count(*[_type == "ravintola" && references(^._id)]) > 0]\n    | order(name asc){\n      name,\n      "slug": slug.current,\n      country,\n      maakunta,\n      "count": count(*[_type == "ravintola" && references(^._id) && closed != true])\n    },\n  "cuisines": array::unique(*[_type == "ravintola" && defined(cuisine)].cuisine[]),\n  "total": count(*[_type == "ravintola" && defined(slug.current) && closed != true]),\n  "closedCount": count(*[_type == "ravintola" && closed == true]),\n  "firstVisitYear": *[_type == "ravintola" && defined(visitedAt)]\n    | order(visitedAt asc)[0].visitedAt\n}': RavintolatFacetsQueryResult;
    '\n  *[_type == "ravintola" && slug.current == $slug][0]{\n    \n  _id,\n  name,\n  "slug": slug.current,\n  "city": city->{ name, "slug": slug.current, country },\n  stars,\n  ratingOverall,\n  ratingFood,\n  ratingPrice,\n  ratingAtmosphere,\n  priceLevel,\n  cuisine,\n  closed,\n  tiivistelma,\n  tuomio,\n  stadionHuomio,\n  "image": images[0]\n,\n    _updatedAt,\n    address,\n    postalCode,\n    phone,\n    website,\n    location,\n    closedNote,\n    pros,\n    cons,\n    visitedAt,\n    visits,\n    visitContext,\n    review,\n    ottelupaivana,\n    images,\n    seoTitle,\n    seoDescription,\n    "userReviews": *[_type == "ravintolaKayttajaArvostelu"\n      && restaurant._ref == ^._id]\n      | order(submittedAt desc){\n        _id,\n        reviewerName,\n        stars,\n        comment,\n        submittedAt\n      },\n    "related": *[_type == "ravintola" && defined(slug.current)\n      && _id != ^._id && closed != true && city._ref == ^.city._ref]\n      | order(coalesce(ratingOverall, stars, 0) desc, name asc)[0...3]{\n  _id,\n  name,\n  "slug": slug.current,\n  "city": city->{ name, "slug": slug.current, country },\n  stars,\n  ratingOverall,\n  ratingFood,\n  ratingPrice,\n  ratingAtmosphere,\n  priceLevel,\n  cuisine,\n  closed,\n  tiivistelma,\n  tuomio,\n  stadionHuomio,\n  "image": images[0]\n}\n  }\n': RavintolaBySlugQueryResult;
    '\n  *[_type == "ravintola" && defined(slug.current)].slug.current\n': RavintolaSlugsQueryResult;
    '\n  *[_type == "ravintola" && defined(slug.current)] | order(name asc){\n    _id,\n    name,\n    "slug": slug.current,\n    "city": city->name\n  }\n': RavintolaOptionsQueryResult;
    '\n  *[_type == $type && defined(slug.current)] | order(_updatedAt desc) {\n    "slug": slug.current,\n    "updatedAt": _updatedAt\n  }\n': SitemapByTypeQueryResult;
    '\n  *[_type == "jalkapalloTilasto" && defined(slug.current)] | order(_updatedAt desc) {\n    _id,\n    _type,\n    "slug": slug.current,\n    category,\n    huuhkajatOsio,\n    "parent": *[\n      _type in ["arvokisa", "pelaaja", "klubiToiminta", "sivu"]\n      && references(^._id)\n      && !(_id in path("drafts.**"))\n    ] | order(_type asc, _id asc)[0]{ _type, "slug": slug.current },\n    "updatedAt": _updatedAt\n  }\n': SitemapTilastotQueryResult;
    '\n  *[_type == "uutinen" && defined(publishedAt)]\n    | order(publishedAt desc) {\n      "slug": string::split(publishedAt, "-")[0],\n      "updatedAt": _updatedAt\n    }\n': SitemapArchiveYearsQueryResult;
    '\n  {\n    "items": *[_type == "uutinen" && defined(slug.current) && ($category == null || $category in categories)] | order(publishedAt desc)[$start...$end]{\n      _id,\n      title,\n      "slug": slug.current,\n      publishedAt,\n      excerpt,\n      tiivistelma,\n      coverImage,\n      categories\n    },\n    "total": count(*[_type == "uutinen" && defined(slug.current) && ($category == null || $category in categories)])\n  }\n': UutisetPageQueryResult;
    '\n  array::unique(*[_type == "uutinen" && defined(slug.current)].categories[])\n': UutisetCategoriesQueryResult;
    '\n  *[_type == "uutinen" && defined(slug.current)].slug.current\n': UutinenSlugsQueryResult;
    '\n  *[_type == "uutinen" && defined(slug.current) && slug.current == $slug][0]{\n      _id,\n      title,\n      "slug": slug.current,\n      publishedAt,\n      excerpt,\n      tiivistelma,\n      coverImage,\n      categories,\n    _updatedAt,\n    body,\n    lahde{ nimi, url, pvm },\n    ulkoinenLinkki,\n    "author": author->{ name, role },\n    kommentointi{ kaytossa, tyyppi, sulkeutuu, vaihtoehdot, sijoituksia, maalikuningas, ohje },\n    seoTitle,\n    seoDescription\n  }\n': UutinenDetailQueryResult;
    '\n  *[_type == "uutinen" && defined(slug.current) && slug.current != $slug\n    && count((categories[])[@ in $categories]) > 0]\n    | order(publishedAt desc)[0...$count]{\n      _id,\n      title,\n      "slug": slug.current,\n      publishedAt,\n      excerpt,\n      tiivistelma,\n      coverImage,\n      categories\n  }\n': RelatedUutisetQueryResult;
    '\n  *[_type == "uutinen" && defined(slug.current) && defined(publishedAt)]{\n    "year": string::split(publishedAt, "-")[0]\n  }\n': UutisetArchiveYearsQueryResult;
    '\n  {\n    "items": *[_type == "uutinen" && defined(slug.current) && publishedAt >= $from && publishedAt < $to]\n      | order(publishedAt desc)[$start...$end]{\n      _id,\n      title,\n      "slug": slug.current,\n      publishedAt,\n      excerpt,\n      tiivistelma,\n      coverImage,\n      categories\n    },\n    "total": count(*[_type == "uutinen" && defined(slug.current) && publishedAt >= $from && publishedAt < $to])\n  }\n': UutisetByYearQueryResult;
    '\n  *[_type == "tapahtuma" && defined(slug.current) && startsAt >= now()] | order(startsAt asc){\n      _id,\n      title,\n      "slug": slug.current,\n      startsAt,\n      endsAt,\n      location,\n      tiivistelma,\n      juhla,\n      image\n  }\n': TulevatTapahtumatQueryResult;
    '\n  *[_type == "tapahtuma" && defined(slug.current) && startsAt < now()] | order(startsAt desc){\n      _id,\n      title,\n      "slug": slug.current,\n      startsAt,\n      endsAt,\n      location,\n      tiivistelma,\n      juhla,\n      image\n  }\n': MenneetTapahtumatQueryResult;
    '\n  *[_type == "tapahtuma" && defined(slug.current)].slug.current\n': TapahtumaSlugsQueryResult;
    '\n  *[_type == "tapahtuma" && defined(slug.current) && slug.current == $slug][0]{\n      _id,\n      title,\n      "slug": slug.current,\n      startsAt,\n      endsAt,\n      location,\n      tiivistelma,\n      juhla,\n      image,\n    _updatedAt,\n    description,\n    signupUrl,\n    signupEmail,\n    seoTitle,\n    seoDescription\n  }\n': TapahtumaDetailQueryResult;
  }
}
